# Default values for statefulset-affinity-injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

podAnnotations: {}
podLabels: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}
