# Default values for statefulset-affinity-injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

podAnnotations: {}
podLabels: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}


webhook:
  # only resources in namespaces that match the namespace selector may trigger the webhook
  namespaceSelector: {}
  # triggering objects must also match the object labels
  objectSelector: {}

  timeoutSeconds: 30
